[package]
name = "avro2adf-schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.12"
once_cell = "1.18.0"
serde_json = "1.0.107"
test-case = "3.2.1"

